use kayak_core::CursorIcon;

pub fn convert_cursor_icon(cursor_icon: CursorIcon) -> bevy::prelude::CursorIcon {
    match cursor_icon {
        CursorIcon::Default => bevy::prelude::CursorIcon::Default,
        CursorIcon::Crosshair => bevy::prelude::CursorIcon::Crosshair,
        CursorIcon::Hand => bevy::prelude::CursorIcon::Hand,
        CursorIcon::Arrow => bevy::prelude::CursorIcon::Arrow,
        CursorIcon::Move => bevy::prelude::CursorIcon::Move,
        CursorIcon::Text => bevy::prelude::CursorIcon::Text,
        CursorIcon::Wait => bevy::prelude::CursorIcon::Wait,
        CursorIcon::Help => bevy::prelude::CursorIcon::Help,
        CursorIcon::Progress => bevy::prelude::CursorIcon::Progress,
        CursorIcon::NotAllowed => bevy::prelude::CursorIcon::NotAllowed,
        CursorIcon::ContextMenu => bevy::prelude::CursorIcon::ContextMenu,
        CursorIcon::Cell => bevy::prelude::CursorIcon::Cell,
        CursorIcon::VerticalText => bevy::prelude::CursorIcon::VerticalText,
        CursorIcon::Alias => bevy::prelude::CursorIcon::Alias,
        CursorIcon::Copy => bevy::prelude::CursorIcon::Copy,
        CursorIcon::NoDrop => bevy::prelude::CursorIcon::NoDrop,
        CursorIcon::Grab => bevy::prelude::CursorIcon::Grab,
        CursorIcon::Grabbing => bevy::prelude::CursorIcon::Grabbing,
        CursorIcon::AllScroll => bevy::prelude::CursorIcon::AllScroll,
        CursorIcon::ZoomIn => bevy::prelude::CursorIcon::ZoomIn,
        CursorIcon::ZoomOut => bevy::prelude::CursorIcon::ZoomOut,
        CursorIcon::EResize => bevy::prelude::CursorIcon::EResize,
        CursorIcon::NResize => bevy::prelude::CursorIcon::NResize,
        CursorIcon::NeResize => bevy::prelude::CursorIcon::NeResize,
        CursorIcon::NwResize => bevy::prelude::CursorIcon::NwResize,
        CursorIcon::SResize => bevy::prelude::CursorIcon::SResize,
        CursorIcon::SeResize => bevy::prelude::CursorIcon::SeResize,
        CursorIcon::SwResize => bevy::prelude::CursorIcon::SwResize,
        CursorIcon::WResize => bevy::prelude::CursorIcon::WResize,
        CursorIcon::EwResize => bevy::prelude::CursorIcon::EwResize,
        CursorIcon::NsResize => bevy::prelude::CursorIcon::NsResize,
        CursorIcon::NeswResize => bevy::prelude::CursorIcon::NeswResize,
        CursorIcon::NwseResize => bevy::prelude::CursorIcon::NwseResize,
        CursorIcon::ColResize => bevy::prelude::CursorIcon::ColResize,
        CursorIcon::RowResize => bevy::prelude::CursorIcon::RowResize,
    }
}